name: CI Pipeline - DEV Environment

on:
  push:
    branches:
      - ventas

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Node.js, Npm, and Git
      run: |
        sudo apt update
        sudo apt install -y nodejs npm git

    - name: Create Working Directory on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_PUBLICA_EC2 }}
        username: ${{ secrets.HOST_NAME }}
        key: ${{ secrets.KEY_PEM_PC }}
        script: |
          sudo rm -rf /opt/patriciacayo || true
          sudo mkdir -p /opt/patriciacayo
          sudo chown -R $USER:$USER /opt/patriciacayo

    - name: Clone Repository
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_PUBLICA_EC2 }}
        username: ${{ secrets.HOST_NAME }}
        key: ${{ secrets.KEY_PEM_PC }}
        script: |
          sudo git clone https://${{ secrets.GH_TOKEN }}@github.com/usuario/repo /opt/patriciacayo

    - name: Install NPM Packages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_PUBLICA_EC2 }}
        username: ${{ secrets.HOST_NAME }}
        key: ${{ secrets.KEY_PEM_PC }}
        script: |
          cd /opt/patriciacayo
          sudo npm install express pm2

    - name: Start Node Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_PUBLICA_EC2 }}
        username: ${{ secrets.HOST_NAME }}
        key: ${{ secrets.KEY_PEM_PC }}
        script: |
          cd /opt/patriciacayo
          sudo pm2 start app.js

    - name: Check Application Status
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_PUBLICA_EC2 }}
        username: ${{ secrets.HOST_NAME }}
        key: ${{ secrets.KEY_PEM_PC }}
        script: |
          sudo pm2 status app.js
